/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'background': '#0b0b0f',
        'surface': '#111116',
        'surface-dim': '#0e0e13',
        'surface-bright': '#1e1e24',
        'surface-variant': '#14141b',
        'surface-container-lowest': '#07070a',
        'surface-container-low': '#0d0d12',
        'surface-container': '#111117',
        'surface-container-high': '#171720',
        'surface-container-highest': '#20202b',
        'on-surface': '#f3f4f6',
        'on-surface-variant': '#cbd5e1',
        'on-background': '#f3f4f6',
        'primary': '#6366f1',
        'on-primary': '#ffffff',
        'primary-container': '#1e1b4b',
        'on-primary-container': '#cbd5e1',
        'primary-fixed': '#cbd5e1',
        'primary-fixed-dim': '#a5b4fc',
        'on-primary-fixed': '#0f172a',
        'on-primary-fixed-variant': '#312e81',
        'inverse-primary': '#4f46e5',
        'secondary': '#94a3b8',
        'on-secondary': '#0f172a',
        'secondary-container': '#1e293b',
        'on-secondary-container': '#e2e8f0',
        'secondary-fixed': '#f1f5f9',
        'secondary-fixed-dim': '#94a3b8',
        'on-secondary-fixed': '#0f172a',
        'on-secondary-fixed-variant': '#1e293b',
        'tertiary': '#f59e0b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#78350f',
        'on-tertiary-container': '#fde68a',
        'tertiary-fixed': '#fde68a',
        'tertiary-fixed-dim': '#f59e0b',
        'on-tertiary-fixed': '#451a03',
        'on-tertiary-fixed-variant': '#78350f',
        'error': '#f25c54',
        'on-error': '#ffffff',
        'error-container': '#7f1d1d',
        'on-error-container': '#fee2e2',
        'outline': '#475569',
        'outline-variant': '#334155',
        'inverse-surface': '#f3f4f6',
        'inverse-on-surface': '#0f172a',
        'surface-tint': '#6366f1',
        'border-subtle': '#1f1f2a',
        'text-muted': '#64748b',
        'signal-rose': '#f25c54',
        'signal-amber': '#fbbf24',
        'signal-emerald': '#34d399',
        'signal-cyan': '#38bdf8',
      },
      borderRadius: {
        DEFAULT: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        gutter: '12px',
        'sidebar-width': '260px',
        'inspector-width': '320px',
        'row-height-dense': '28px',
        'row-height-standard': '36px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'code-md': ['JetBrains Mono', 'monospace'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '700' }],
        'code-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'code-sm': ['11px', { lineHeight: '14px', fontWeight: '400' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
