"""Initial schema

Revision ID: b50c314edd77
Revises: 
Create Date: 2026-07-16 22:02:46.357035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50c314edd77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_path', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('references_json', sa.Text(), nullable=True),
    sa.Column('supporting_metrics_json', sa.Text(), nullable=True),
    sa.Column('graph_references_json', sa.Text(), nullable=True),
    sa.Column('source_locations_json', sa.Text(), nullable=True),
    sa.Column('line_numbers_json', sa.Text(), nullable=True),
    sa.Column('reasoning_chain_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidence_type_file', 'evidence', ['type', 'file_path'], unique=False)
    op.create_index(op.f('ix_evidence_file_path'), 'evidence', ['file_path'], unique=False)
    op.create_index(op.f('ix_evidence_repo_path'), 'evidence', ['repo_path'], unique=False)
    op.create_index(op.f('ix_evidence_source'), 'evidence', ['source'], unique=False)
    op.create_index(op.f('ix_evidence_type'), 'evidence', ['type'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('supporting_evidence_json', sa.Text(), nullable=True),
    sa.Column('affected_entities_json', sa.Text(), nullable=True),
    sa.Column('recommendations_json', sa.Text(), nullable=True),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('visualization_hints_json', sa.Text(), nullable=True),
    sa.Column('actions_json', sa.Text(), nullable=True),
    sa.Column('related_insights_json', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_category'), 'insights', ['category'], unique=False)
    op.create_index(op.f('ix_insights_file_path'), 'insights', ['file_path'], unique=False)
    op.create_index(op.f('ix_insights_severity'), 'insights', ['severity'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('members_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refactoring_pipelines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tasks_json', sa.Text(), nullable=False),
    sa.Column('impact_report_json', sa.Text(), nullable=False),
    sa.Column('execution_history_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refactoring_pipelines_status'), 'refactoring_pipelines', ['status'], unique=False)
    op.create_table('repositories',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('analyzed_at', sa.String(), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('source_files', sa.Integer(), nullable=True),
    sa.Column('commits', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_repositories_path'), 'repositories', ['path'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repo_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assignees_json', sa.Text(), nullable=False),
    sa.Column('files_json', sa.Text(), nullable=False),
    sa.Column('comments_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('entities',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('repo_uid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('properties_json', sa.Text(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_uid'], ['repositories.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('idx_entities_kind_file', 'entities', ['kind', 'file_path'], unique=False)
    op.create_index(op.f('ix_entities_file_path'), 'entities', ['file_path'], unique=False)
    op.create_index(op.f('ix_entities_kind'), 'entities', ['kind'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_index(op.f('ix_entities_repo_uid'), 'entities', ['repo_uid'], unique=False)
    op.create_table('relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_uid', sa.String(), nullable=False),
    sa.Column('target_uid', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_uid'], ['entities.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_uid'], ['entities.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_uid', 'target_uid', 'kind', name='uq_source_target_kind')
    )
    op.create_index(op.f('ix_relations_kind'), 'relations', ['kind'], unique=False)
    op.create_index(op.f('ix_relations_source_uid'), 'relations', ['source_uid'], unique=False)
    op.create_index(op.f('ix_relations_target_uid'), 'relations', ['target_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relations_target_uid'), table_name='relations')
    op.drop_index(op.f('ix_relations_source_uid'), table_name='relations')
    op.drop_index(op.f('ix_relations_kind'), table_name='relations')
    op.drop_table('relations')
    op.drop_index(op.f('ix_entities_repo_uid'), table_name='entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_kind'), table_name='entities')
    op.drop_index(op.f('ix_entities_file_path'), table_name='entities')
    op.drop_index('idx_entities_kind_file', table_name='entities')
    op.drop_table('entities')
    op.drop_table('settings')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_repositories_path'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_refactoring_pipelines_status'), table_name='refactoring_pipelines')
    op.drop_table('refactoring_pipelines')
    op.drop_table('organization_teams')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_insights_severity'), table_name='insights')
    op.drop_index(op.f('ix_insights_file_path'), table_name='insights')
    op.drop_index(op.f('ix_insights_category'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_source'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_repo_path'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_file_path'), table_name='evidence')
    op.drop_index('idx_evidence_type_file', table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
